// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { VisualTrackAPI } from './visualtrack-api'
import { VisualTrack, CopyVisualTrackToVisualTrackAPI } from './visualtrack'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { LayerGroupAPI } from './layergroup-api'
import { DivIconAPI } from './divicon-api'

@Injectable({
  providedIn: 'root'
})
export class VisualTrackService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  VisualTrackServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private visualtracksUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.visualtracksUrl = origin + '/api/github.com/fullstack-lang/gongleaflet/go/v1/visualtracks';
  }

  /** GET visualtracks from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<VisualTrackAPI[]> {
    return this.getVisualTracks(GONG__StackPath, frontRepo)
  }
  getVisualTracks(GONG__StackPath: string, frontRepo: FrontRepo): Observable<VisualTrackAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<VisualTrackAPI[]>(this.visualtracksUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<VisualTrackAPI[]>('getVisualTracks', []))
      );
  }

  /** GET visualtrack by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<VisualTrackAPI> {
    return this.getVisualTrack(id, GONG__StackPath, frontRepo)
  }
  getVisualTrack(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<VisualTrackAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.visualtracksUrl}/${id}`;
    return this.http.get<VisualTrackAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched visualtrack id=${id}`)),
      catchError(this.handleError<VisualTrackAPI>(`getVisualTrack id=${id}`))
    );
  }

  // postFront copy visualtrack to a version with encoded pointers and post to the back
  postFront(visualtrack: VisualTrack, GONG__StackPath: string): Observable<VisualTrackAPI> {
    let visualtrackAPI = new VisualTrackAPI
    CopyVisualTrackToVisualTrackAPI(visualtrack, visualtrackAPI)
    const id = typeof visualtrackAPI === 'number' ? visualtrackAPI : visualtrackAPI.ID
    const url = `${this.visualtracksUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<VisualTrackAPI>(url, visualtrackAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<VisualTrackAPI>('postVisualTrack'))
    );
  }
  
  /** POST: add a new visualtrack to the server */
  post(visualtrackdb: VisualTrackAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<VisualTrackAPI> {
    return this.postVisualTrack(visualtrackdb, GONG__StackPath, frontRepo)
  }
  postVisualTrack(visualtrackdb: VisualTrackAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<VisualTrackAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<VisualTrackAPI>(this.visualtracksUrl, visualtrackdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted visualtrackdb id=${visualtrackdb.ID}`)
      }),
      catchError(this.handleError<VisualTrackAPI>('postVisualTrack'))
    );
  }

  /** DELETE: delete the visualtrackdb from the server */
  delete(visualtrackdb: VisualTrackAPI | number, GONG__StackPath: string): Observable<VisualTrackAPI> {
    return this.deleteVisualTrack(visualtrackdb, GONG__StackPath)
  }
  deleteVisualTrack(visualtrackdb: VisualTrackAPI | number, GONG__StackPath: string): Observable<VisualTrackAPI> {
    const id = typeof visualtrackdb === 'number' ? visualtrackdb : visualtrackdb.ID;
    const url = `${this.visualtracksUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<VisualTrackAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted visualtrackdb id=${id}`)),
      catchError(this.handleError<VisualTrackAPI>('deleteVisualTrack'))
    );
  }

  // updateFront copy visualtrack to a version with encoded pointers and update to the back
  updateFront(visualtrack: VisualTrack, GONG__StackPath: string): Observable<VisualTrackAPI> {
    let visualtrackAPI = new VisualTrackAPI
    CopyVisualTrackToVisualTrackAPI(visualtrack, visualtrackAPI)
    const id = typeof visualtrackAPI === 'number' ? visualtrackAPI : visualtrackAPI.ID
    const url = `${this.visualtracksUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<VisualTrackAPI>(url, visualtrackAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<VisualTrackAPI>('updateVisualTrack'))
    );
  }

  /** PUT: update the visualtrackdb on the server */
  update(visualtrackdb: VisualTrackAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<VisualTrackAPI> {
    return this.updateVisualTrack(visualtrackdb, GONG__StackPath, frontRepo)
  }
  updateVisualTrack(visualtrackdb: VisualTrackAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<VisualTrackAPI> {
    const id = typeof visualtrackdb === 'number' ? visualtrackdb : visualtrackdb.ID;
    const url = `${this.visualtracksUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<VisualTrackAPI>(url, visualtrackdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated visualtrackdb id=${visualtrackdb.ID}`)
      }),
      catchError(this.handleError<VisualTrackAPI>('updateVisualTrack'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in VisualTrackService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("VisualTrackService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
