// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, NullInt64, SelectionMode } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { VisualTrackDB } from '../visualtrack-db'
import { VisualTrackService } from '../visualtrack.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-visualtrackstable',
  templateUrl: './visualtracks-table.component.html',
  styleUrls: ['./visualtracks-table.component.css'],
})
export class VisualTracksTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode

  // used if the component is called as a selection component of VisualTrack instances
  selection: SelectionModel<VisualTrackDB>;
  initialSelection = new Array<VisualTrackDB>();

  // the data source for the table
  visualtracks: VisualTrackDB[];
  matTableDataSource: MatTableDataSource<VisualTrackDB>

  // front repo, that will be referenced by this.visualtracks
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (visualtrackDB: VisualTrackDB, property: string) => {
      switch (property) {
        // insertion point for specific sorting accessor
        case 'Lat':
          return visualtrackDB.Lat;

        case 'Lng':
          return visualtrackDB.Lng;

        case 'Heading':
          return visualtrackDB.Heading;

        case 'Level':
          return visualtrackDB.Level;

        case 'Speed':
          return visualtrackDB.Speed;

        case 'VerticalSpeed':
          return visualtrackDB.VerticalSpeed;

        case 'Name':
          return visualtrackDB.Name;

        case 'VisualColorEnum':
          return visualtrackDB.VisualColorEnum;

        case 'VisualLayer':
          return (visualtrackDB.VisualLayer ? visualtrackDB.VisualLayer.Name : '');

        case 'VisualIcon':
          return (visualtrackDB.VisualIcon ? visualtrackDB.VisualIcon.Name : '');

        case 'Display':
          return visualtrackDB.Display;

        case 'DisplayTrackHistory':
          return visualtrackDB.DisplayTrackHistory;

        case 'DisplayLevelAndSpeed':
          return visualtrackDB.DisplayLevelAndSpeed;

        default:
          return VisualTrackDB[property];
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (visualtrackDB: VisualTrackDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the visualtrackDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += visualtrackDB.Lat.toString()
      mergedContent += visualtrackDB.Lng.toString()
      mergedContent += visualtrackDB.Heading.toString()
      mergedContent += visualtrackDB.Level.toString()
      mergedContent += visualtrackDB.Speed.toString()
      mergedContent += visualtrackDB.VerticalSpeed.toString()
      mergedContent += visualtrackDB.Name.toLowerCase()
      mergedContent += visualtrackDB.VisualColorEnum.toLowerCase()
      if (visualtrackDB.VisualLayer) {
        mergedContent += visualtrackDB.VisualLayer.Name.toLowerCase()
      }
      if (visualtrackDB.VisualIcon) {
        mergedContent += visualtrackDB.VisualIcon.Name.toLowerCase()
      }

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private visualtrackService: VisualTrackService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of visualtrack instances
    public dialogRef: MatDialogRef<VisualTracksTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.visualtrackService.VisualTrackServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getVisualTracks()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Lat",
        "Lng",
        "Heading",
        "Level",
        "Speed",
        "VerticalSpeed",
        "Name",
        "VisualColorEnum",
        "VisualLayer",
        "VisualIcon",
        "Display",
        "DisplayTrackHistory",
        "DisplayLevelAndSpeed",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Lat",
        "Lng",
        "Heading",
        "Level",
        "Speed",
        "VerticalSpeed",
        "Name",
        "VisualColorEnum",
        "VisualLayer",
        "VisualIcon",
        "Display",
        "DisplayTrackHistory",
        "DisplayLevelAndSpeed",
      ]
      this.selection = new SelectionModel<VisualTrackDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getVisualTracks()
    this.matTableDataSource = new MatTableDataSource(this.visualtracks)
  }

  getVisualTracks(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.visualtracks = this.frontRepo.VisualTracks_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          this.visualtracks.forEach(
            visualtrack => {
              let ID = this.dialogData.ID
              let revPointer = visualtrack[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(visualtrack)
              }
            }
          )
          this.selection = new SelectionModel<VisualTrackDB>(allowMultiSelect, this.initialSelection);
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

          if (sourceInstance[this.dialogData.SourceField]) {
            for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
              let visualtrack = associationInstance[this.dialogData.IntermediateStructField]
              this.initialSelection.push(visualtrack)
            }
          }
          this.selection = new SelectionModel<VisualTrackDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.visualtracks
      }
    )
  }

  // newVisualTrack initiate a new visualtrack
  // create a new VisualTrack objet
  newVisualTrack() {
  }

  deleteVisualTrack(visualtrackID: number, visualtrack: VisualTrackDB) {
    // list of visualtracks is truncated of visualtrack before the delete
    this.visualtracks = this.visualtracks.filter(h => h !== visualtrack);

    this.visualtrackService.deleteVisualTrack(visualtrackID).subscribe(
      visualtrack => {
        this.visualtrackService.VisualTrackServiceChanged.next("delete")
      }
    );
  }

  editVisualTrack(visualtrackID: number, visualtrack: VisualTrackDB) {

  }

  // display visualtrack in router
  displayVisualTrackInRouter(visualtrackID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongleaflet_go-" + "visualtrack-display", visualtrackID])
  }

  // set editor outlet
  setEditorRouterOutlet(visualtrackID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongleaflet_go_editor: ["github_com_fullstack_lang_gongleaflet_go-" + "visualtrack-detail", visualtrackID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(visualtrackID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongleaflet_go_presentation: ["github_com_fullstack_lang_gongleaflet_go-" + "visualtrack-presentation", visualtrackID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.visualtracks.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.visualtracks.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<VisualTrackDB>()

      // reset all initial selection of visualtrack that belong to visualtrack
      this.initialSelection.forEach(
        visualtrack => {
          visualtrack[this.dialogData.ReversePointer].Int64 = 0
          visualtrack[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(visualtrack)
        }
      )

      // from selection, set visualtrack that belong to visualtrack
      this.selection.selected.forEach(
        visualtrack => {
          let ID = +this.dialogData.ID
          visualtrack[this.dialogData.ReversePointer].Int64 = ID
          visualtrack[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(visualtrack)
        }
      )

      // update all visualtrack (only update selection & initial selection)
      toUpdate.forEach(
        visualtrack => {
          this.visualtrackService.updateVisualTrack(visualtrack)
            .subscribe(visualtrack => {
              this.visualtrackService.VisualTrackServiceChanged.next("update")
            });
        }
      )
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedVisualTrack = new Set<number>()
      for (let visualtrack of this.initialSelection) {
        if (this.selection.selected.includes(visualtrack)) {
          // console.log("visualtrack " + visualtrack.Name + " is still selected")
        } else {
          console.log("visualtrack " + visualtrack.Name + " has been unselected")
          unselectedVisualTrack.add(visualtrack.ID)
          console.log("is unselected " + unselectedVisualTrack.has(visualtrack.ID))
        }
      }

      // delete the association instance
      if (sourceInstance[this.dialogData.SourceField]) {
        for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
          let visualtrack = associationInstance[this.dialogData.IntermediateStructField]
          if (unselectedVisualTrack.has(visualtrack.ID)) {

            this.frontRepoService.deleteService( this.dialogData.IntermediateStruct, associationInstance )
          }
        }
      }

      // is the source array is emptyn create it
      if (sourceInstance[this.dialogData.SourceField] == undefined) {
        sourceInstance[this.dialogData.SourceField] = new Array<any>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField]) {
        this.selection.selected.forEach(
          visualtrack => {
            if (!this.initialSelection.includes(visualtrack)) {
              // console.log("visualtrack " + visualtrack.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + visualtrack.Name,
              }

              associationInstance[this.dialogData.IntermediateStructField+"ID"] = new NullInt64
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Int64 = visualtrack.ID
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Valid = true

              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"] = new NullInt64
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Int64 = sourceInstance["ID"]
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Valid = true

              this.frontRepoService.postService( this.dialogData.IntermediateStruct, associationInstance )

            } else {
              // console.log("visualtrack " + visualtrack.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<VisualTrackDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
