// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { VisualCenterDB } from '../visualcenter-db'
import { VisualCenterService } from '../visualcenter.service'

import { FrontRepoService, FrontRepo, NullInt64 } from '../front-repo.service'
@Component({
  selector: 'lib-visualcenter-sorting',
  templateUrl: './visualcenter-sorting.component.html',
  styleUrls: ['./visualcenter-sorting.component.css']
})
export class VisualCenterSortingComponent implements OnInit {

  frontRepo: FrontRepo

  // array of VisualCenter instances that are in the association
  associatedVisualCenters = new Array<VisualCenterDB>();

  constructor(
    private visualcenterService: VisualCenterService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of visualcenter instances
    public dialogRef: MatDialogRef<VisualCenterSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getVisualCenters()
  }

  getVisualCenters(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let visualcenter of this.frontRepo.VisualCenters_array) {
          let ID = this.dialogData.ID
          let revPointerID = visualcenter[this.dialogData.ReversePointer]
          let revPointerID_Index = visualcenter[this.dialogData.ReversePointer+"_Index"]
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedVisualCenters.push(visualcenter)
          }
        }

        // sort associated visualcenter according to order
        this.associatedVisualCenters.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer+"_Index"]
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer+"_Index"]
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }  
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedVisualCenters, event.previousIndex, event.currentIndex);

    // set the order of VisualCenter instances
    let index = 0
    
    for (let visualcenter of this.associatedVisualCenters) {
      let revPointerID_Index = visualcenter[this.dialogData.ReversePointer+"_Index"]
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedVisualCenters.forEach(
      visualcenter => {
        this.visualcenterService.updateVisualCenter(visualcenter)
          .subscribe(visualcenter => {
            this.visualcenterService.VisualCenterServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of '+ this.dialogData.ReversePointer+' done');
  }
}
