// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { VisualCenterDB } from '../visualcenter-db'
import { VisualCenterService } from '../visualcenter.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-visualcenterstable',
  templateUrl: './visualcenters-table.component.html',
  styleUrls: ['./visualcenters-table.component.css'],
})
export class VisualCentersTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of VisualCenter instances
  selection: SelectionModel<VisualCenterDB> = new (SelectionModel)
  initialSelection = new Array<VisualCenterDB>()

  // the data source for the table
  visualcenters: VisualCenterDB[] = []
  matTableDataSource: MatTableDataSource<VisualCenterDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.visualcenters
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (visualcenterDB: VisualCenterDB, property: string) => {
      switch (property) {
        case 'ID':
          return visualcenterDB.ID

        // insertion point for specific sorting accessor
        case 'Lat':
          return visualcenterDB.Lat;

        case 'Lng':
          return visualcenterDB.Lng;

        case 'Name':
          return visualcenterDB.Name;

        case 'VisualColorEnum':
          return visualcenterDB.VisualColorEnum;

        case 'VisualLayer':
          return (visualcenterDB.VisualLayer ? visualcenterDB.VisualLayer.Name : '');

        case 'DivIcon':
          return (visualcenterDB.DivIcon ? visualcenterDB.DivIcon.Name : '');

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (visualcenterDB: VisualCenterDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the visualcenterDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += visualcenterDB.Lat.toString()
      mergedContent += visualcenterDB.Lng.toString()
      mergedContent += visualcenterDB.Name.toLowerCase()
      mergedContent += visualcenterDB.VisualColorEnum.toLowerCase()
      if (visualcenterDB.VisualLayer) {
        mergedContent += visualcenterDB.VisualLayer.Name.toLowerCase()
      }
      if (visualcenterDB.DivIcon) {
        mergedContent += visualcenterDB.DivIcon.Name.toLowerCase()
      }

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private visualcenterService: VisualCenterService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of visualcenter instances
    public dialogRef: MatDialogRef<VisualCentersTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.visualcenterService.VisualCenterServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getVisualCenters()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Lat",
        "Lng",
        "Name",
        "VisualColorEnum",
        "VisualLayer",
        "DivIcon",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Lat",
        "Lng",
        "Name",
        "VisualColorEnum",
        "VisualLayer",
        "DivIcon",
      ]
      this.selection = new SelectionModel<VisualCenterDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getVisualCenters()
    this.matTableDataSource = new MatTableDataSource(this.visualcenters)
  }

  getVisualCenters(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.visualcenters = this.frontRepo.VisualCenters_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let visualcenter of this.visualcenters) {
            let ID = this.dialogData.ID
            let revPointer = visualcenter[this.dialogData.ReversePointer as keyof VisualCenterDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(visualcenter)
            }
            this.selection = new SelectionModel<VisualCenterDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, VisualCenterDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as VisualCenterDB[]
          for (let associationInstance of sourceField) {
            let visualcenter = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as VisualCenterDB
            this.initialSelection.push(visualcenter)
          }

          this.selection = new SelectionModel<VisualCenterDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.visualcenters
      }
    )
  }

  // newVisualCenter initiate a new visualcenter
  // create a new VisualCenter objet
  newVisualCenter() {
  }

  deleteVisualCenter(visualcenterID: number, visualcenter: VisualCenterDB) {
    // list of visualcenters is truncated of visualcenter before the delete
    this.visualcenters = this.visualcenters.filter(h => h !== visualcenter);

    this.visualcenterService.deleteVisualCenter(visualcenterID).subscribe(
      visualcenter => {
        this.visualcenterService.VisualCenterServiceChanged.next("delete")
      }
    );
  }

  editVisualCenter(visualcenterID: number, visualcenter: VisualCenterDB) {

  }

  // display visualcenter in router
  displayVisualCenterInRouter(visualcenterID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongleaflet_go-" + "visualcenter-display", visualcenterID])
  }

  // set editor outlet
  setEditorRouterOutlet(visualcenterID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongleaflet_go_editor: ["github_com_fullstack_lang_gongleaflet_go-" + "visualcenter-detail", visualcenterID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(visualcenterID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongleaflet_go_presentation: ["github_com_fullstack_lang_gongleaflet_go-" + "visualcenter-presentation", visualcenterID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.visualcenters.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.visualcenters.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<VisualCenterDB>()

      // reset all initial selection of visualcenter that belong to visualcenter
      for (let visualcenter of this.initialSelection) {
        let index = visualcenter[this.dialogData.ReversePointer as keyof VisualCenterDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(visualcenter)

      }

      // from selection, set visualcenter that belong to visualcenter
      for (let visualcenter of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = visualcenter[this.dialogData.ReversePointer as keyof VisualCenterDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(visualcenter)
      }


      // update all visualcenter (only update selection & initial selection)
      for (let visualcenter of toUpdate) {
        this.visualcenterService.updateVisualCenter(visualcenter)
          .subscribe(visualcenter => {
            this.visualcenterService.VisualCenterServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, VisualCenterDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedVisualCenter = new Set<number>()
      for (let visualcenter of this.initialSelection) {
        if (this.selection.selected.includes(visualcenter)) {
          // console.log("visualcenter " + visualcenter.Name + " is still selected")
        } else {
          console.log("visualcenter " + visualcenter.Name + " has been unselected")
          unselectedVisualCenter.add(visualcenter.ID)
          console.log("is unselected " + unselectedVisualCenter.has(visualcenter.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let visualcenter = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as VisualCenterDB
      if (unselectedVisualCenter.has(visualcenter.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<VisualCenterDB>) = new Array<VisualCenterDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          visualcenter => {
            if (!this.initialSelection.includes(visualcenter)) {
              // console.log("visualcenter " + visualcenter.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + visualcenter.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = visualcenter.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = visualcenter.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("visualcenter " + visualcenter.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<VisualCenterDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
