// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { VisualLineDB } from '../visualline-db'
import { VisualLineService } from '../visualline.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-visuallines-table',
  templateUrl: './visuallines-table.component.html',
  styleUrls: ['./visuallines-table.component.css'],
})
export class VisualLinesTableComponent implements OnInit {

  // used if the component is called as a selection component of VisualLine instances
  selection: SelectionModel<VisualLineDB>;
  initialSelection = new Array<VisualLineDB>();

  // the data source for the table
  visuallines: VisualLineDB[];
  matTableDataSource: MatTableDataSource<VisualLineDB>


  // front repo, that will be referenced by this.visuallines
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {
    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private visuallineService: VisualLineService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of visualline instances
    public dialogRef: MatDialogRef<VisualLinesTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // observable for changes in structs
    this.visuallineService.VisualLineServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getVisualLines()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "StartLat",
        "StartLng",
        "EndLat",
        "EndLng",
        "Name",
        "VisualColorEnum",
        "DashStyleEnum",
        "VisualLayer",
        "IsTransmitting",
        "Message",
        "IsTransmittingBackward",
        "MessageBackward",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "StartLat",
        "StartLng",
        "EndLat",
        "EndLng",
        "Name",
        "VisualColorEnum",
        "DashStyleEnum",
        "VisualLayer",
        "IsTransmitting",
        "Message",
        "IsTransmittingBackward",
        "MessageBackward",
      ]
      this.selection = new SelectionModel<VisualLineDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getVisualLines()
    this.matTableDataSource = new MatTableDataSource(this.visuallines)
  }

  getVisualLines(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.visuallines = this.frontRepo.VisualLines_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.visuallines.forEach(
            visualline => {
              let ID = this.dialogData.ID
              let revPointer = visualline[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(visualline)
              }
            }
          )
          this.selection = new SelectionModel<VisualLineDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.visuallines
      }
    )
  }

  // newVisualLine initiate a new visualline
  // create a new VisualLine objet
  newVisualLine() {
  }

  deleteVisualLine(visuallineID: number, visualline: VisualLineDB) {
    // list of visuallines is truncated of visualline before the delete
    this.visuallines = this.visuallines.filter(h => h !== visualline);

    this.visuallineService.deleteVisualLine(visuallineID).subscribe(
      visualline => {
        this.visuallineService.VisualLineServiceChanged.next("delete")
      }
    );
  }

  editVisualLine(visuallineID: number, visualline: VisualLineDB) {

  }

  // display visualline in router
  displayVisualLineInRouter(visuallineID: number) {
    this.router.navigate(["visualline-display", visuallineID])
  }

  // set editor outlet
  setEditorRouterOutlet(visuallineID: number) {
    this.router.navigate([{
      outlets: {
        editor: ["visualline-detail", visuallineID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(visuallineID: number) {
    this.router.navigate([{
      outlets: {
        presentation: ["visualline-presentation", visuallineID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.visuallines.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.visuallines.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<VisualLineDB>()

    // reset all initial selection of visualline that belong to visualline through Anarrayofb
    this.initialSelection.forEach(
      visualline => {
        visualline[this.dialogData.ReversePointer].Int64 = 0
        visualline[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(visualline)
      }
    )

    // from selection, set visualline that belong to visualline through Anarrayofb
    this.selection.selected.forEach(
      visualline => {
        let ID = +this.dialogData.ID
        visualline[this.dialogData.ReversePointer].Int64 = ID
        visualline[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(visualline)
      }
    )

    // update all visualline (only update selection & initial selection)
    toUpdate.forEach(
      visualline => {
        this.visuallineService.updateVisualLine(visualline)
          .subscribe(visualline => {
            this.visuallineService.VisualLineServiceChanged.next("update")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
