// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { VisualMapDB } from '../visualmap-db'
import { VisualMapService } from '../visualmap.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-visualmap-sorting',
  templateUrl: './visualmap-sorting.component.html',
  styleUrls: ['./visualmap-sorting.component.css']
})
export class VisualMapSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of VisualMap instances that are in the association
  associatedVisualMaps = new Array<VisualMapDB>();

  constructor(
    private visualmapService: VisualMapService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of visualmap instances
    public dialogRef: MatDialogRef<VisualMapSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getVisualMaps()
  }

  getVisualMaps(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let visualmap of this.frontRepo.VisualMaps_array) {
          let ID = this.dialogData.ID
          let revPointerID = visualmap[this.dialogData.ReversePointer as keyof VisualMapDB] as unknown as NullInt64
          let revPointerID_Index = visualmap[this.dialogData.ReversePointer + "_Index" as keyof VisualMapDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedVisualMaps.push(visualmap)
          }
        }

        // sort associated visualmap according to order
        this.associatedVisualMaps.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedVisualMaps, event.previousIndex, event.currentIndex);

    // set the order of VisualMap instances
    let index = 0

    for (let visualmap of this.associatedVisualMaps) {
      let revPointerID_Index = visualmap[this.dialogData.ReversePointer + "_Index" as keyof VisualMapDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedVisualMaps.forEach(
      visualmap => {
        this.visualmapService.updateVisualMap(visualmap)
          .subscribe(visualmap => {
            this.visualmapService.VisualMapServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer +' done');
  }
}
