// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { VisualIconDB } from '../visualicon-db'
import { VisualIconService } from '../visualicon.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-visualicon-sorting',
  templateUrl: './visualicon-sorting.component.html',
  styleUrls: ['./visualicon-sorting.component.css']
})
export class VisualIconSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of VisualIcon instances that are in the association
  associatedVisualIcons = new Array<VisualIconDB>();

  constructor(
    private visualiconService: VisualIconService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of visualicon instances
    public dialogRef: MatDialogRef<VisualIconSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getVisualIcons()
  }

  getVisualIcons(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let visualicon of this.frontRepo.VisualIcons_array) {
          let ID = this.dialogData.ID
          let revPointerID = visualicon[this.dialogData.ReversePointer as keyof VisualIconDB] as unknown as NullInt64
          let revPointerID_Index = visualicon[this.dialogData.ReversePointer + "_Index" as keyof VisualIconDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedVisualIcons.push(visualicon)
          }
        }

        // sort associated visualicon according to order
        this.associatedVisualIcons.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedVisualIcons, event.previousIndex, event.currentIndex);

    // set the order of VisualIcon instances
    let index = 0

    for (let visualicon of this.associatedVisualIcons) {
      let revPointerID_Index = visualicon[this.dialogData.ReversePointer + "_Index" as keyof VisualIconDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedVisualIcons.forEach(
      visualicon => {
        this.visualiconService.updateVisualIcon(visualicon)
          .subscribe(visualicon => {
            this.visualiconService.VisualIconServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer +' done');
  }
}
