// generated by stacks/gong/go/models/controller_file.go
package controllers

import (
	"log"
	"net/http"
	"time"

	"github.com/fullstack-lang/gongleaflet/go/models"
	"github.com/fullstack-lang/gongleaflet/go/orm"

	"github.com/gin-gonic/gin"
)

// declaration in order to justify use of the models import
var __MapOptions__dummysDeclaration__ models.MapOptions
var __MapOptions_time__dummyDeclaration time.Duration

// An MapOptionsID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getMapOptions updateMapOptions deleteMapOptions
type MapOptionsID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// MapOptionsInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postMapOptions updateMapOptions
type MapOptionsInput struct {
	// The MapOptions to submit or modify
	// in: body
	MapOptions *orm.MapOptionsAPI
}

// GetMapOptionss
//
// swagger:route GET /mapoptionss mapoptionss getMapOptionss
//
// # Get all mapoptionss
//
// Responses:
// default: genericError
//
//	200: mapoptionsDBResponse
func GetMapOptionss(c *gin.Context) {
	db := orm.BackRepo.BackRepoMapOptions.GetDB()

	// source slice
	var mapoptionsDBs []orm.MapOptionsDB

	// type Values map[string][]string
	values := c.Request.URL.Query()
	if len(values) == 1 {
		value := values["GONG__StackPath"]
		if len(value) == 1 {
			// we have a single parameter
			// we assume it is the stack
			stackParam := value[0]
			log.Println("GONG__StackPath", stackParam)
		}
	}

	query := db.Find(&mapoptionsDBs)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// slice that will be transmitted to the front
	mapoptionsAPIs := make([]orm.MapOptionsAPI, 0)

	// for each mapoptions, update fields from the database nullable fields
	for idx := range mapoptionsDBs {
		mapoptionsDB := &mapoptionsDBs[idx]
		_ = mapoptionsDB
		var mapoptionsAPI orm.MapOptionsAPI

		// insertion point for updating fields
		mapoptionsAPI.ID = mapoptionsDB.ID
		mapoptionsDB.CopyBasicFieldsToMapOptions(&mapoptionsAPI.MapOptions)
		mapoptionsAPI.MapOptionsPointersEnconding = mapoptionsDB.MapOptionsPointersEnconding
		mapoptionsAPIs = append(mapoptionsAPIs, mapoptionsAPI)
	}

	c.JSON(http.StatusOK, mapoptionsAPIs)
}

// PostMapOptions
//
// swagger:route POST /mapoptionss mapoptionss postMapOptions
//
// Creates a mapoptions
//
//	Consumes:
//	- application/json
//
//	Produces:
//	- application/json
//
//	Responses:
//	  200: nodeDBResponse
func PostMapOptions(c *gin.Context) {

	// Validate input
	var input orm.MapOptionsAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create mapoptions
	mapoptionsDB := orm.MapOptionsDB{}
	mapoptionsDB.MapOptionsPointersEnconding = input.MapOptionsPointersEnconding
	mapoptionsDB.CopyBasicFieldsFromMapOptions(&input.MapOptions)

	db := orm.BackRepo.BackRepoMapOptions.GetDB()
	query := db.Create(&mapoptionsDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	orm.BackRepo.BackRepoMapOptions.CheckoutPhaseOneInstance(&mapoptionsDB)
	mapoptions := (*orm.BackRepo.BackRepoMapOptions.Map_MapOptionsDBID_MapOptionsPtr)[mapoptionsDB.ID]

	if mapoptions != nil {
		models.AfterCreateFromFront(&models.Stage, mapoptions)
	}

	// a POST is equivalent to a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, mapoptionsDB)
}

// GetMapOptions
//
// swagger:route GET /mapoptionss/{ID} mapoptionss getMapOptions
//
// Gets the details for a mapoptions.
//
// Responses:
// default: genericError
//
//	200: mapoptionsDBResponse
func GetMapOptions(c *gin.Context) {

	// type Values map[string][]string
	values := c.Request.URL.Query()
	if len(values) == 1 {
		value := values["stack"]
		if len(value) == 1 {
			// we have a single parameter
			// we assume it is the stack
			stackParam := value[0]
			log.Println("GET params", stackParam)
		}
	}

	db := orm.BackRepo.BackRepoMapOptions.GetDB()

	// Get mapoptionsDB in DB
	var mapoptionsDB orm.MapOptionsDB
	if err := db.First(&mapoptionsDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	var mapoptionsAPI orm.MapOptionsAPI
	mapoptionsAPI.ID = mapoptionsDB.ID
	mapoptionsAPI.MapOptionsPointersEnconding = mapoptionsDB.MapOptionsPointersEnconding
	mapoptionsDB.CopyBasicFieldsToMapOptions(&mapoptionsAPI.MapOptions)

	c.JSON(http.StatusOK, mapoptionsAPI)
}

// UpdateMapOptions
//
// swagger:route PATCH /mapoptionss/{ID} mapoptionss updateMapOptions
//
// # Update a mapoptions
//
// Responses:
// default: genericError
//
//	200: mapoptionsDBResponse
func UpdateMapOptions(c *gin.Context) {

	// Validate input
	var input orm.MapOptionsAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	db := orm.BackRepo.BackRepoMapOptions.GetDB()

	// Get model if exist
	var mapoptionsDB orm.MapOptionsDB

	// fetch the mapoptions
	query := db.First(&mapoptionsDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// update
	mapoptionsDB.CopyBasicFieldsFromMapOptions(&input.MapOptions)
	mapoptionsDB.MapOptionsPointersEnconding = input.MapOptionsPointersEnconding

	query = db.Model(&mapoptionsDB).Updates(mapoptionsDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	mapoptionsNew := new(models.MapOptions)
	mapoptionsDB.CopyBasicFieldsToMapOptions(mapoptionsNew)

	// get stage instance from DB instance, and call callback function
	mapoptionsOld := (*orm.BackRepo.BackRepoMapOptions.Map_MapOptionsDBID_MapOptionsPtr)[mapoptionsDB.ID]
	if mapoptionsOld != nil {
		models.AfterUpdateFromFront(&models.Stage, mapoptionsOld, mapoptionsNew)
	}

	// an UPDATE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	// in some cases, with the marshalling of the stage, this operation might
	// generates a checkout
	orm.BackRepo.IncrementPushFromFrontNb()

	// return status OK with the marshalling of the the mapoptionsDB
	c.JSON(http.StatusOK, mapoptionsDB)
}

// DeleteMapOptions
//
// swagger:route DELETE /mapoptionss/{ID} mapoptionss deleteMapOptions
//
// # Delete a mapoptions
//
// default: genericError
//
//	200: mapoptionsDBResponse
func DeleteMapOptions(c *gin.Context) {
	db := orm.BackRepo.BackRepoMapOptions.GetDB()

	// Get model if exist
	var mapoptionsDB orm.MapOptionsDB
	if err := db.First(&mapoptionsDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&mapoptionsDB)

	// get an instance (not staged) from DB instance, and call callback function
	mapoptionsDeleted := new(models.MapOptions)
	mapoptionsDB.CopyBasicFieldsToMapOptions(mapoptionsDeleted)

	// get stage instance from DB instance, and call callback function
	mapoptionsStaged := (*orm.BackRepo.BackRepoMapOptions.Map_MapOptionsDBID_MapOptionsPtr)[mapoptionsDB.ID]
	if mapoptionsStaged != nil {
		models.AfterDeleteFromFront(&models.Stage, mapoptionsStaged, mapoptionsDeleted)
	}

	// a DELETE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, gin.H{"data": true})
}
