// generated by stacks/gong/go/models/controller_file.go
package controllers

import (
	"net/http"
	"time"

	"github.com/fullstack-lang/gongleaflet/go/models"
	"github.com/fullstack-lang/gongleaflet/go/orm"

	"github.com/gin-gonic/gin"
	"github.com/jinzhu/gorm"
)

// declaration in order to justify use of the models import
var __VisualMap__dummysDeclaration__ models.VisualMap
var __VisualMap_time__dummyDeclaration time.Duration

// An VisualMapID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getVisualMap updateVisualMap deleteVisualMap
type VisualMapID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// VisualMapInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postVisualMap updateVisualMap
type VisualMapInput struct {
	// The VisualMap to submit or modify
	// in: body
	VisualMap *orm.VisualMapAPI
}

// GetVisualMaps
//
// swagger:route GET /visualmaps visualmaps getVisualMaps
//
// Get all visualmaps
//
// Responses:
//    default: genericError
//        200: visualmapDBsResponse
func GetVisualMaps(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	var visualmaps []orm.VisualMapDB
	query := db.Find(&visualmaps)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// for each visualmap, update fields from the database nullable fields
	for idx := range visualmaps {
		visualmap := &visualmaps[idx]
		_ = visualmap
		// insertion point for updating fields
		if visualmap.Lat_Data.Valid {
			visualmap.Lat = visualmap.Lat_Data.Float64
		}

		if visualmap.Lng_Data.Valid {
			visualmap.Lng = visualmap.Lng_Data.Float64
		}

		if visualmap.Name_Data.Valid {
			visualmap.Name = visualmap.Name_Data.String
		}

		if visualmap.ZoomLevel_Data.Valid {
			visualmap.ZoomLevel = visualmap.ZoomLevel_Data.Float64
		}

		if visualmap.UrlTemplate_Data.Valid {
			visualmap.UrlTemplate = visualmap.UrlTemplate_Data.String
		}

		if visualmap.Attribution_Data.Valid {
			visualmap.Attribution = visualmap.Attribution_Data.String
		}

		if visualmap.MaxZoom_Data.Valid {
			visualmap.MaxZoom = int(visualmap.MaxZoom_Data.Int64)
		}

		visualmap.ZoomControl = visualmap.ZoomControl_Data.Bool

		visualmap.AttributionControl = visualmap.AttributionControl_Data.Bool

		visualmap.ZoomSnap = visualmap.ZoomSnap_Data.Bool

	}

	c.JSON(http.StatusOK, visualmaps)
}

// PostVisualMap
//
// swagger:route POST /visualmaps visualmaps postVisualMap
//
// Creates a visualmap
//     Consumes:
//     - application/json
//
//     Produces:
//     - application/json
//
//     Responses:
//       200: visualmapDBResponse
func PostVisualMap(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Validate input
	var input orm.VisualMapAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create visualmap
	visualmapDB := orm.VisualMapDB{}
	visualmapDB.VisualMapAPI = input
	// insertion point for nullable field set
	visualmapDB.Lat_Data.Float64 = input.Lat
	visualmapDB.Lat_Data.Valid = true

	visualmapDB.Lng_Data.Float64 = input.Lng
	visualmapDB.Lng_Data.Valid = true

	visualmapDB.Name_Data.String = input.Name
	visualmapDB.Name_Data.Valid = true

	visualmapDB.ZoomLevel_Data.Float64 = input.ZoomLevel
	visualmapDB.ZoomLevel_Data.Valid = true

	visualmapDB.UrlTemplate_Data.String = input.UrlTemplate
	visualmapDB.UrlTemplate_Data.Valid = true

	visualmapDB.Attribution_Data.String = input.Attribution
	visualmapDB.Attribution_Data.Valid = true

	visualmapDB.MaxZoom_Data.Int64 = int64(input.MaxZoom)
	visualmapDB.MaxZoom_Data.Valid = true

	visualmapDB.ZoomControl_Data.Bool = input.ZoomControl
	visualmapDB.ZoomControl_Data.Valid = true

	visualmapDB.AttributionControl_Data.Bool = input.AttributionControl
	visualmapDB.AttributionControl_Data.Valid = true

	visualmapDB.ZoomSnap_Data.Bool = input.ZoomSnap
	visualmapDB.ZoomSnap_Data.Valid = true

	query := db.Create(&visualmapDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// a POST is equivalent to a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementCommitNb()

	c.JSON(http.StatusOK, visualmapDB)
}

// GetVisualMap
//
// swagger:route GET /visualmaps/{ID} visualmaps getVisualMap
//
// Gets the details for a visualmap.
//
// Responses:
//    default: genericError
//        200: visualmapDBResponse
func GetVisualMap(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Get visualmap in DB
	var visualmap orm.VisualMapDB
	if err := db.First(&visualmap, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// insertion point for fields value set from nullable fields
	if visualmap.Lat_Data.Valid {
		visualmap.Lat = visualmap.Lat_Data.Float64
	}

	if visualmap.Lng_Data.Valid {
		visualmap.Lng = visualmap.Lng_Data.Float64
	}

	if visualmap.Name_Data.Valid {
		visualmap.Name = visualmap.Name_Data.String
	}

	if visualmap.ZoomLevel_Data.Valid {
		visualmap.ZoomLevel = visualmap.ZoomLevel_Data.Float64
	}

	if visualmap.UrlTemplate_Data.Valid {
		visualmap.UrlTemplate = visualmap.UrlTemplate_Data.String
	}

	if visualmap.Attribution_Data.Valid {
		visualmap.Attribution = visualmap.Attribution_Data.String
	}

	if visualmap.MaxZoom_Data.Valid {
		visualmap.MaxZoom = int(visualmap.MaxZoom_Data.Int64)
	}

	visualmap.ZoomControl = visualmap.ZoomControl_Data.Bool

	visualmap.AttributionControl = visualmap.AttributionControl_Data.Bool

	visualmap.ZoomSnap = visualmap.ZoomSnap_Data.Bool

	c.JSON(http.StatusOK, visualmap)
}

// UpdateVisualMap
//
// swagger:route PATCH /visualmaps/{ID} visualmaps updateVisualMap
//
// Update a visualmap
//
// Responses:
//    default: genericError
//        200: visualmapDBResponse
func UpdateVisualMap(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Get model if exist
	var visualmapDB orm.VisualMapDB

	// fetch the visualmap
	query := db.First(&visualmapDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Validate input
	var input orm.VisualMapAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// update
	// insertion point for nullable field set
	input.Lat_Data.Float64 = input.Lat
	input.Lat_Data.Valid = true

	input.Lng_Data.Float64 = input.Lng
	input.Lng_Data.Valid = true

	input.Name_Data.String = input.Name
	input.Name_Data.Valid = true

	input.ZoomLevel_Data.Float64 = input.ZoomLevel
	input.ZoomLevel_Data.Valid = true

	input.UrlTemplate_Data.String = input.UrlTemplate
	input.UrlTemplate_Data.Valid = true

	input.Attribution_Data.String = input.Attribution
	input.Attribution_Data.Valid = true

	input.MaxZoom_Data.Int64 = int64(input.MaxZoom)
	input.MaxZoom_Data.Valid = true

	input.ZoomControl_Data.Bool = input.ZoomControl
	input.ZoomControl_Data.Valid = true

	input.AttributionControl_Data.Bool = input.AttributionControl
	input.AttributionControl_Data.Valid = true

	input.ZoomSnap_Data.Bool = input.ZoomSnap
	input.ZoomSnap_Data.Valid = true

	query = db.Model(&visualmapDB).Updates(input)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// an UPDATE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementCommitNb()

	// return status OK with the marshalling of the the visualmapDB
	c.JSON(http.StatusOK, visualmapDB)
}

// DeleteVisualMap
//
// swagger:route DELETE /visualmaps/{ID} visualmaps deleteVisualMap
//
// Delete a visualmap
//
// Responses:
//    default: genericError
func DeleteVisualMap(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Get model if exist
	var visualmapDB orm.VisualMapDB
	if err := db.First(&visualmapDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&visualmapDB)

	// a DELETE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementCommitNb()

	c.JSON(http.StatusOK, gin.H{"data": true})
}
