// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { MarkerDB } from './marker-db';

// insertion point for imports
import { LayerGroupDB } from './layergroup-db'
import { DivIconDB } from './divicon-db'

@Injectable({
  providedIn: 'root'
})
export class MarkerService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  MarkerServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private markersUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.markersUrl = origin + '/api/github.com/fullstack-lang/gongleaflet/go/v1/markers';
  }

  /** GET markers from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string): Observable<MarkerDB[]> {
    return this.getMarkers(GONG__StackPath)
  }
  getMarkers(GONG__StackPath: string): Observable<MarkerDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<MarkerDB[]>(this.markersUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched markers')),
        catchError(this.handleError<MarkerDB[]>('getMarkers', []))
      );
  }

  /** GET marker by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string): Observable<MarkerDB> {
	return this.getMarker(id, GONG__StackPath)
  }
  getMarker(id: number, GONG__StackPath: string): Observable<MarkerDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.markersUrl}/${id}`;
    return this.http.get<MarkerDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched marker id=${id}`)),
      catchError(this.handleError<MarkerDB>(`getMarker id=${id}`))
    );
  }

  /** POST: add a new marker to the server */
  post(markerdb: MarkerDB, GONG__StackPath: string): Observable<MarkerDB> {
    return this.postMarker(markerdb, GONG__StackPath)	
  }
  postMarker(markerdb: MarkerDB, GONG__StackPath: string): Observable<MarkerDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    let LayerGroup = markerdb.LayerGroup
    markerdb.LayerGroup = new LayerGroupDB
    let DivIcon = markerdb.DivIcon
    markerdb.DivIcon = new DivIconDB

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<MarkerDB>(this.markersUrl, markerdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`posted markerdb id=${markerdb.ID}`)
      }),
      catchError(this.handleError<MarkerDB>('postMarker'))
    );
  }

  /** DELETE: delete the markerdb from the server */
  delete(markerdb: MarkerDB | number, GONG__StackPath: string): Observable<MarkerDB> {
    return this.deleteMarker(markerdb, GONG__StackPath)
  }
  deleteMarker(markerdb: MarkerDB | number, GONG__StackPath: string): Observable<MarkerDB> {
    const id = typeof markerdb === 'number' ? markerdb : markerdb.ID;
    const url = `${this.markersUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<MarkerDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted markerdb id=${id}`)),
      catchError(this.handleError<MarkerDB>('deleteMarker'))
    );
  }

  /** PUT: update the markerdb on the server */
  update(markerdb: MarkerDB, GONG__StackPath: string): Observable<MarkerDB> {
    return this.updateMarker(markerdb, GONG__StackPath)
  }
  updateMarker(markerdb: MarkerDB, GONG__StackPath: string): Observable<MarkerDB> {
    const id = typeof markerdb === 'number' ? markerdb : markerdb.ID;
    const url = `${this.markersUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    let LayerGroup = markerdb.LayerGroup
    markerdb.LayerGroup = new LayerGroupDB
    let DivIcon = markerdb.DivIcon
    markerdb.DivIcon = new DivIconDB

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<MarkerDB>(url, markerdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`updated markerdb id=${markerdb.ID}`)
      }),
      catchError(this.handleError<MarkerDB>('updateMarker'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in MarkerService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("MarkerService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
