// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { UserClickDB } from './userclick-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class UserClickService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  UserClickServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private userclicksUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.userclicksUrl = origin + '/api/github.com/fullstack-lang/gongleaflet/go/v1/userclicks';
  }

  /** GET userclicks from the server */
  getUserClicks(GONG__StackPath: string): Observable<UserClickDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<UserClickDB[]>(this.userclicksUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched userclicks')),
        catchError(this.handleError<UserClickDB[]>('getUserClicks', []))
      );
  }

  /** GET userclick by id. Will 404 if id not found */
  getUserClick(id: number, GONG__StackPath: string): Observable<UserClickDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.userclicksUrl}/${id}`;
    return this.http.get<UserClickDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched userclick id=${id}`)),
      catchError(this.handleError<UserClickDB>(`getUserClick id=${id}`))
    );
  }

  /** POST: add a new userclick to the server */
  postUserClick(userclickdb: UserClickDB, GONG__StackPath: string): Observable<UserClickDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<UserClickDB>(this.userclicksUrl, userclickdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`posted userclickdb id=${userclickdb.ID}`)
      }),
      catchError(this.handleError<UserClickDB>('postUserClick'))
    );
  }

  /** DELETE: delete the userclickdb from the server */
  deleteUserClick(userclickdb: UserClickDB | number, GONG__StackPath: string): Observable<UserClickDB> {
    const id = typeof userclickdb === 'number' ? userclickdb : userclickdb.ID;
    const url = `${this.userclicksUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<UserClickDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted userclickdb id=${id}`)),
      catchError(this.handleError<UserClickDB>('deleteUserClick'))
    );
  }

  /** PUT: update the userclickdb on the server */
  updateUserClick(userclickdb: UserClickDB, GONG__StackPath: string): Observable<UserClickDB> {
    const id = typeof userclickdb === 'number' ? userclickdb : userclickdb.ID;
    const url = `${this.userclicksUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<UserClickDB>(url, userclickdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`updated userclickdb id=${userclickdb.ID}`)
      }),
      catchError(this.handleError<UserClickDB>('updateUserClick'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in UserClickService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("UserClickService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
