// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { VisualIconDB } from './visualicon-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class VisualIconService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  VisualIconServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private visualiconsUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.visualiconsUrl = origin + '/api/github.com/fullstack-lang/gongleaflet/go/v1/visualicons';
  }

  /** GET visualicons from the server */
  getVisualIcons(): Observable<VisualIconDB[]> {
    return this.http.get<VisualIconDB[]>(this.visualiconsUrl)
      .pipe(
        tap(_ => this.log('fetched visualicons')),
        catchError(this.handleError<VisualIconDB[]>('getVisualIcons', []))
      );
  }

  /** GET visualicon by id. Will 404 if id not found */
  getVisualIcon(id: number): Observable<VisualIconDB> {
    const url = `${this.visualiconsUrl}/${id}`;
    return this.http.get<VisualIconDB>(url).pipe(
      tap(_ => this.log(`fetched visualicon id=${id}`)),
      catchError(this.handleError<VisualIconDB>(`getVisualIcon id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new visualicon to the server */
  postVisualIcon(visualicondb: VisualIconDB): Observable<VisualIconDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.post<VisualIconDB>(this.visualiconsUrl, visualicondb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`posted visualicondb id=${visualicondb.ID}`)
      }),
      catchError(this.handleError<VisualIconDB>('postVisualIcon'))
    );
  }

  /** DELETE: delete the visualicondb from the server */
  deleteVisualIcon(visualicondb: VisualIconDB | number): Observable<VisualIconDB> {
    const id = typeof visualicondb === 'number' ? visualicondb : visualicondb.ID;
    const url = `${this.visualiconsUrl}/${id}`;

    return this.http.delete<VisualIconDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted visualicondb id=${id}`)),
      catchError(this.handleError<VisualIconDB>('deleteVisualIcon'))
    );
  }

  /** PUT: update the visualicondb on the server */
  updateVisualIcon(visualicondb: VisualIconDB): Observable<VisualIconDB> {
    const id = typeof visualicondb === 'number' ? visualicondb : visualicondb.ID;
    const url = `${this.visualiconsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.put<VisualIconDB>(url, visualicondb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated visualicondb id=${visualicondb.ID}`)
      }),
      catchError(this.handleError<VisualIconDB>('updateVisualIcon'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
