// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { VisualLineDB } from './visualline-db';

// insertion point for imports
import { VisualLayerDB } from './visuallayer-db'
import { VisualMapDB } from './visualmap-db'

@Injectable({
  providedIn: 'root'
})
export class VisualLineService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  VisualLineServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private visuallinesUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.visuallinesUrl = origin + '/api/github.com/fullstack-lang/gongleaflet/go/v1/visuallines';
  }

  /** GET visuallines from the server */
  getVisualLines(): Observable<VisualLineDB[]> {
    return this.http.get<VisualLineDB[]>(this.visuallinesUrl)
      .pipe(
        tap(_ => this.log('fetched visuallines')),
        catchError(this.handleError<VisualLineDB[]>('getVisualLines', []))
      );
  }

  /** GET visualline by id. Will 404 if id not found */
  getVisualLine(id: number): Observable<VisualLineDB> {
    const url = `${this.visuallinesUrl}/${id}`;
    return this.http.get<VisualLineDB>(url).pipe(
      tap(_ => this.log(`fetched visualline id=${id}`)),
      catchError(this.handleError<VisualLineDB>(`getVisualLine id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new visualline to the server */
  postVisualLine(visuallinedb: VisualLineDB): Observable<VisualLineDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    visuallinedb.VisualLayer = new VisualLayerDB
    let _VisualMap_VisualLines_reverse = visuallinedb.VisualMap_VisualLines_reverse
    visuallinedb.VisualMap_VisualLines_reverse = new VisualMapDB

    return this.http.post<VisualLineDB>(this.visuallinesUrl, visuallinedb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        visuallinedb.VisualMap_VisualLines_reverse = _VisualMap_VisualLines_reverse
        this.log(`posted visuallinedb id=${visuallinedb.ID}`)
      }),
      catchError(this.handleError<VisualLineDB>('postVisualLine'))
    );
  }

  /** DELETE: delete the visuallinedb from the server */
  deleteVisualLine(visuallinedb: VisualLineDB | number): Observable<VisualLineDB> {
    const id = typeof visuallinedb === 'number' ? visuallinedb : visuallinedb.ID;
    const url = `${this.visuallinesUrl}/${id}`;

    return this.http.delete<VisualLineDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted visuallinedb id=${id}`)),
      catchError(this.handleError<VisualLineDB>('deleteVisualLine'))
    );
  }

  /** PUT: update the visuallinedb on the server */
  updateVisualLine(visuallinedb: VisualLineDB): Observable<VisualLineDB> {
    const id = typeof visuallinedb === 'number' ? visuallinedb : visuallinedb.ID;
    const url = `${this.visuallinesUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    visuallinedb.VisualLayer = new VisualLayerDB
    let _VisualMap_VisualLines_reverse = visuallinedb.VisualMap_VisualLines_reverse
    visuallinedb.VisualMap_VisualLines_reverse = new VisualMapDB

    return this.http.put<VisualLineDB>(url, visuallinedb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        visuallinedb.VisualMap_VisualLines_reverse = _VisualMap_VisualLines_reverse
        this.log(`updated visuallinedb id=${visuallinedb.ID}`)
      }),
      catchError(this.handleError<VisualLineDB>('updateVisualLine'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
