// generated by genORMTranslation.go
package orm

import (
	"bufio"
	"bytes"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"

	"gorm.io/gorm"

	"github.com/fullstack-lang/gongleaflet/go/models"

	"github.com/tealeg/xlsx/v3"
)

// BackRepoStruct supports callback functions
type BackRepoStruct struct {
	// insertion point for per struct back repo declarations
	BackRepoVisualCenter BackRepoVisualCenterStruct

	BackRepoVisualCircle BackRepoVisualCircleStruct

	BackRepoVisualIcon BackRepoVisualIconStruct

	BackRepoVisualLayer BackRepoVisualLayerStruct

	BackRepoVisualLine BackRepoVisualLineStruct

	BackRepoVisualMap BackRepoVisualMapStruct

	BackRepoVisualTrack BackRepoVisualTrackStruct

	CommitNb uint // this ng is updated at the BackRepo level but also at the BackRepo<GongStruct> level
}

func (backRepo *BackRepoStruct) GetLastCommitNb() uint {
	return backRepo.CommitNb
}

func (backRepo *BackRepoStruct) IncrementCommitNb() uint {
	if models.Stage.OnInitCommitCallback != nil {
		models.Stage.OnInitCommitCallback.BeforeCommit(&models.Stage)
	}
	backRepo.CommitNb = backRepo.CommitNb + 1
	return backRepo.CommitNb
}

// Init the BackRepoStruct inner variables and link to the database
func (backRepo *BackRepoStruct) Init(db *gorm.DB) {
	// insertion point for per struct back repo declarations
	backRepo.BackRepoVisualCenter.Init(db)
	backRepo.BackRepoVisualCircle.Init(db)
	backRepo.BackRepoVisualIcon.Init(db)
	backRepo.BackRepoVisualLayer.Init(db)
	backRepo.BackRepoVisualLine.Init(db)
	backRepo.BackRepoVisualMap.Init(db)
	backRepo.BackRepoVisualTrack.Init(db)

	models.Stage.BackRepo = backRepo
}

// Commit the BackRepoStruct inner variables and link to the database
func (backRepo *BackRepoStruct) Commit(stage *models.StageStruct) {
	// insertion point for per struct back repo phase one commit
	backRepo.BackRepoVisualCenter.CommitPhaseOne(stage)
	backRepo.BackRepoVisualCircle.CommitPhaseOne(stage)
	backRepo.BackRepoVisualIcon.CommitPhaseOne(stage)
	backRepo.BackRepoVisualLayer.CommitPhaseOne(stage)
	backRepo.BackRepoVisualLine.CommitPhaseOne(stage)
	backRepo.BackRepoVisualMap.CommitPhaseOne(stage)
	backRepo.BackRepoVisualTrack.CommitPhaseOne(stage)

	// insertion point for per struct back repo phase two commit
	backRepo.BackRepoVisualCenter.CommitPhaseTwo(backRepo)
	backRepo.BackRepoVisualCircle.CommitPhaseTwo(backRepo)
	backRepo.BackRepoVisualIcon.CommitPhaseTwo(backRepo)
	backRepo.BackRepoVisualLayer.CommitPhaseTwo(backRepo)
	backRepo.BackRepoVisualLine.CommitPhaseTwo(backRepo)
	backRepo.BackRepoVisualMap.CommitPhaseTwo(backRepo)
	backRepo.BackRepoVisualTrack.CommitPhaseTwo(backRepo)

	backRepo.IncrementCommitNb()
}

// Checkout the database into the stage
func (backRepo *BackRepoStruct) Checkout(stage *models.StageStruct) {
	// insertion point for per struct back repo phase one commit
	backRepo.BackRepoVisualCenter.CheckoutPhaseOne()
	backRepo.BackRepoVisualCircle.CheckoutPhaseOne()
	backRepo.BackRepoVisualIcon.CheckoutPhaseOne()
	backRepo.BackRepoVisualLayer.CheckoutPhaseOne()
	backRepo.BackRepoVisualLine.CheckoutPhaseOne()
	backRepo.BackRepoVisualMap.CheckoutPhaseOne()
	backRepo.BackRepoVisualTrack.CheckoutPhaseOne()

	// insertion point for per struct back repo phase two commit
	backRepo.BackRepoVisualCenter.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoVisualCircle.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoVisualIcon.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoVisualLayer.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoVisualLine.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoVisualMap.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoVisualTrack.CheckoutPhaseTwo(backRepo)
}

var BackRepo BackRepoStruct

func GetLastCommitNb() uint {
	return BackRepo.GetLastCommitNb()
}

// Backup the BackRepoStruct
func (backRepo *BackRepoStruct) Backup(stage *models.StageStruct, dirPath string) {
	os.Mkdir(dirPath, os.ModePerm)

	// insertion point for per struct backup
	backRepo.BackRepoVisualCenter.Backup(dirPath)
	backRepo.BackRepoVisualCircle.Backup(dirPath)
	backRepo.BackRepoVisualIcon.Backup(dirPath)
	backRepo.BackRepoVisualLayer.Backup(dirPath)
	backRepo.BackRepoVisualLine.Backup(dirPath)
	backRepo.BackRepoVisualMap.Backup(dirPath)
	backRepo.BackRepoVisualTrack.Backup(dirPath)
}

// Backup in XL the BackRepoStruct
func (backRepo *BackRepoStruct) BackupXL(stage *models.StageStruct, dirPath string) {
	os.Mkdir(dirPath, os.ModePerm)

	// open an existing file
	file := xlsx.NewFile()

	// insertion point for per struct backup
	backRepo.BackRepoVisualCenter.BackupXL(file)
	backRepo.BackRepoVisualCircle.BackupXL(file)
	backRepo.BackRepoVisualIcon.BackupXL(file)
	backRepo.BackRepoVisualLayer.BackupXL(file)
	backRepo.BackRepoVisualLine.BackupXL(file)
	backRepo.BackRepoVisualMap.BackupXL(file)
	backRepo.BackRepoVisualTrack.BackupXL(file)

	var b bytes.Buffer
	writer := bufio.NewWriter(&b)
	file.Write(writer)
	theBytes := b.Bytes()

	filename := filepath.Join(dirPath, "bckp.xlsx")
	err := ioutil.WriteFile(filename, theBytes, 0644)
	if err != nil {
		log.Panic("Cannot write the XL file", err.Error())
	}
}

// Restore the database into the back repo
func (backRepo *BackRepoStruct) Restore(stage *models.StageStruct, dirPath string) {
	models.Stage.Commit()
	models.Stage.Reset()
	models.Stage.Checkout()

	//
	// restauration first phase (create DB instance with new IDs)
	//

	// insertion point for per struct backup
	backRepo.BackRepoVisualCenter.RestorePhaseOne(dirPath)
	backRepo.BackRepoVisualCircle.RestorePhaseOne(dirPath)
	backRepo.BackRepoVisualIcon.RestorePhaseOne(dirPath)
	backRepo.BackRepoVisualLayer.RestorePhaseOne(dirPath)
	backRepo.BackRepoVisualLine.RestorePhaseOne(dirPath)
	backRepo.BackRepoVisualMap.RestorePhaseOne(dirPath)
	backRepo.BackRepoVisualTrack.RestorePhaseOne(dirPath)

	//
	// restauration second phase (reindex pointers with the new ID)
	//
	
	// insertion point for per struct backup
	backRepo.BackRepoVisualCenter.RestorePhaseTwo()
	backRepo.BackRepoVisualCircle.RestorePhaseTwo()
	backRepo.BackRepoVisualIcon.RestorePhaseTwo()
	backRepo.BackRepoVisualLayer.RestorePhaseTwo()
	backRepo.BackRepoVisualLine.RestorePhaseTwo()
	backRepo.BackRepoVisualMap.RestorePhaseTwo()
	backRepo.BackRepoVisualTrack.RestorePhaseTwo()

	models.Stage.Checkout()
}

// Restore the database into the back repo
func (backRepo *BackRepoStruct) RestoreXL(stage *models.StageStruct, dirPath string) {
}
